import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#171a19',
  '--slot4-page-text': '#f7f2e9',
  '--slot4-panel-bg': '#1f2321',
  '--slot4-surface-bg': '#202422',
  '--slot4-muted-text': '#b7b0a5',
  '--slot4-soft-muted-text': '#7f817b',
  '--slot4-accent': '#EAC696',
  '--slot4-accent-fill': '#EAC696',
  '--slot4-accent-secondary': '#C8AE7D',
  '--slot4-accent-mid': '#765827',
  '--slot4-accent-deep': '#65451F',
  '--slot4-accent-soft': 'rgba(101,69,31,.42)',
  '--slot4-on-accent': '#17130e',
  '--slot4-dark-bg': '#0b0d0c',
  '--slot4-dark-text': '#f7f2e9',
  '--slot4-media-bg': '#292c29',
  '--slot4-cream': '#EAC696',
  '--slot4-warm': '#765827',
  '--slot4-lavender': '#C8AE7D',
  '--slot4-gray': '#202422',
  '--slot4-body-gradient': 'radial-gradient(circle at 14% 9%, rgba(118,88,39,.22), transparent 28%), radial-gradient(circle at 88% 38%, rgba(101,69,31,.14), transparent 24%), linear-gradient(#171a19,#171a19)',
  '--editable-page-bg': '#171a19',
  '--editable-page-text': '#f7f2e9',
  '--editable-container': '1440px',
  '--editable-border': 'rgba(234,198,150,.18)',
  '--editable-nav-bg': '#0b0d0c',
  '--editable-nav-text': '#f7f2e9',
  '--editable-nav-active': '#EAC696',
  '--editable-nav-active-text': '#17130e',
  '--editable-cta-bg': '#EAC696',
  '--editable-cta-text': '#17130e',
  '--editable-search-bg': '#202422',
  '--editable-footer-bg': '#0b0d0c',
  '--editable-footer-text': '#f7f2e9',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]', pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]', panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]', surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]', softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]', accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]', accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]', darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]', mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]', warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]', grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]', darkBorder: 'border-white/10',
  shadow: 'shadow-[0_18px_50px_rgba(0,0,0,.18)]', shadowStrong: 'shadow-[0_28px_90px_rgba(0,0,0,.4)]',
  overlay: 'bg-[linear-gradient(180deg,transparent,rgba(8,10,9,.88))]',
} as const

export const editableDesignContract = {
  shell: { page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`, section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-8 lg:px-12', sectionY: 'py-16 sm:py-20 lg:py-28' },
  layout: { safeGrid: 'grid gap-px md:grid-cols-2 xl:grid-cols-3', featureGrid: 'grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center', rail: 'flex snap-x gap-4 overflow-x-auto pb-5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden', minRailCard: 'w-[280px] shrink-0 snap-start sm:w-[340px]' },
  type: { eyebrow: 'font-mono text-[10px] font-bold uppercase tracking-[0.2em]', heroTitle: 'text-5xl font-black uppercase leading-[.86] tracking-[-.07em] sm:text-7xl lg:text-[6.5rem]', sectionTitle: 'text-4xl font-black uppercase leading-none tracking-[-.05em] sm:text-6xl', body: 'text-base leading-8' },
  surface: { card: `border ${editablePalette.border} ${editablePalette.surfaceBg}`, soft: `border ${editablePalette.border} ${editablePalette.panelBg}`, dark: `border ${editablePalette.darkBorder} ${editablePalette.darkBg} ${editablePalette.darkText}` },
  button: { primary: 'inline-flex items-center justify-center gap-2 border border-[var(--slot4-accent)] bg-[var(--slot4-accent-fill)] px-6 py-3 text-xs font-black uppercase tracking-[.14em] text-[var(--slot4-on-accent)] transition hover:border-[var(--slot4-accent-secondary)] hover:bg-[var(--slot4-accent-secondary)]', secondary: 'inline-flex items-center justify-center gap-2 border border-[var(--editable-border)] px-6 py-3 text-xs font-black uppercase tracking-[.14em] transition hover:border-[var(--slot4-accent-secondary)] hover:text-[var(--slot4-accent-secondary)]', accent: 'inline-flex items-center justify-center gap-2 bg-[var(--slot4-accent-fill)] px-6 py-3 text-xs font-black uppercase tracking-[.14em] text-[var(--slot4-on-accent)] transition hover:bg-[var(--slot4-accent-secondary)]' },
  media: { frame: `relative overflow-hidden ${editablePalette.mediaBg}`, ratio: 'aspect-[4/3]' },
  motion: { lift: 'transition duration-500 hover:-translate-y-1 hover:border-[var(--slot4-accent)]/50 hover:shadow-[0_25px_70px_rgba(0,0,0,.35)]', fade: 'transition duration-300 hover:opacity-70' },
} as const

export const aiLayoutRules = ['Keep dynamic posts intact.', 'Use task-aware links.', 'Use varied editorial card formats.', 'Protect mobile layouts from overflow.'] as const
